name: 'action-spa'
description: 'GitHub Action for Spinnaker Admin tool'
inputs:
  command:
    description: 'Command to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
